language: node_js
branches:
  only:
    - active
    - master
install:
  - npm install -g
  - rm -rf bats
  - git clone https://github.com/sstephenson/bats.git
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
