language: node_js
branches:
  only:
    - active
    - master
install: npm install
after_install: npm link
before_script: echo "running the tests..."
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
