language: node_js
branches:
  only:
    - active
    - master
after_install: npm link
notifications:
  email:
    recipients:
      - om@soundsapiens.com
    on_success: change
    on_failure: always
